export class InfoWordModel {

  constructor(public def: any, public relations: any) {}
}

export const relationNames = {
    0: 'Idée associée',
    1: 'Raffinement sémantique',
    2: 'Raffinement morphologique',
    3: 'Domaine relatif',
    4: 'Partie du discours',
    5: 'Synonyme',
    6: 'Hyperonyme',
    7: 'Antonyme',
    8: 'Hyponyme',
    9: 'Méronyme',
    10: 'Holonyme',
    11: 'Locution',
    13: 'Agent',
    14: 'Patient',
    15: 'Lieu',
    16: 'Instrument',
    17: 'Caractéristique',
    20: 'Magnification',
    21: 'Antimagnification',
    22: 'Famille lexicale',
    23: 'Caractéristique (inverse)',
    24: 'Agent (inverse)',
    25: 'Instrument (inverse)',
    26: 'Patient (inverse)',
    27: 'Domaine relatif (inverse)',
    28: 'Lieu (inverse)',
    30: 'Lieu (action)',
    31: 'Action (lieu)',
    32: 'Sentiment',
    34: 'Manière',
    35: 'Signification',
    37: 'Rôle télique',
    38: 'Agent (rôle)',
    39: 'Verbe -> Action',
    40: 'Action -> Verbe',
    41: 'Conséquence',
    42: 'Cause',
    43: 'Adjectif -> Verbe',
    44: 'Verbe -> Adjectif',
    49: 'Valeur temporelle',
    50: 'Objet -> Matière',
    51: 'Matière -> Objet',
    52: 'Successeur temporel',
    53: 'Production',
    54: 'Résultat',
    55: 'Opposition',
    56: 'Opposition (inverse)',
    57: 'Implication',
    58: 'Quantificateur',
    59: 'Masculin',
    60: 'Féminin',
    61: 'Équivalent',
    62: 'Manière (inverse)',
    63: 'Implication (verbe/action)',
    64: 'Instance',
    65: 'Realisation',
    67: 'Similaire',
    68: 'Élement -> Ensemble',
    69: 'Ensemble -> Élément',
    70: 'Processus -> Agent',
    71: 'Variante',
    72: 'Strictement substituable',
    73: 'Plus petit que...',
    74: 'Plus grand que...',
    75: 'Accompagné de...',
    76: 'Processus -> Patient',
    77: 'Participe passé',
    78: 'Co-hyponymes',
    79: 'Participe présent',
    80: 'Processus -> Instrument',
    99: 'Dérivé morphologique',
    100: 'Auteur',
    101: 'Personnage',
    102: 'Nourriture',
    103: 'Acteur',
    104: 'Mode de déplacement',
    105: 'Interprète',
    106: 'Couleur',
    107: 'Cible',
    108: 'Symptômes',
    109: 'Prédécesseur temporel',
    110: 'Diagnostique',
    111: 'Prédécesseur spatial',
    112: 'Successeur ',
    113: 'Relation (sociale/familliale)',
    114: 'Tributaire (physique/spatial)',
    115: 'Sentiment (inverse)',
    116: 'Lien',
    117: 'Fonction',
    119: 'But (nom/verbe)',
    120: 'Action/Verbe -> But',
    121: 'Possede',
    122: 'Possèdé',
    123: 'Auxiliaire',
    124: 'Prédécesseur logique',
    125: 'Successeur logique',
    126: 'Incompatibilité générique',
    127: 'Incompatibilité',
    129: 'Requis',
    130: 'Instance de...',
    131: 'Concerné par...',
    132: 'Symptômes (inverse)',
    133: 'Unités',
    134: 'Favorise',
    135: 'Circonstances',
    136: 'Oeuvres',
    137: 'Processus -> Agent (inverse)',
    138: 'Processus -> Patient (inverse)',
    139: 'Processus -> Instrument (inverse)',
    149: 'Complément d\'agent',
    150: 'Bénéficiaire',
    151: 'Déscend de (évolution)...',
    152: 'Domaine de substitution',
    153: 'Propriété (nom)',
    154: 'Voix active',
    155: 'Utilise',
    156: 'Est utilisé',
    157: 'Adjectif -> Propriété',
    158: 'Propriété -> Adjectif',
    159: 'Adjectif -> Adverbe',
    160: 'Adverbe -> Adjectif',
    161: 'Homophone',
    162: 'Confusion potentielle',
    163: 'Concerne',
    164: 'Adjectif -> Nom',
    165: 'Nom -> Adjectif',
    166: 'Opinion de...',
    333: 'Translation',
    666: 'TOTAKI',
    777: 'Wikipédia',
    997: 'Annotation d\'exception',
    998: 'Annotation',
    999: 'Inhibition'
  };
